UP = 1
DOWN = 2
RIGHT = 4
LEFT = 8

VERT_MASK = UP | DOWN
HORI_MASK = RIGHT | LEFT
POS_MASK = DOWN | RIGHT
NEG_MASK = UP | LEFT

DIRECTION_TO_NAME = {
    UP: 'UP',
    DOWN: 'DOWN',
    RIGHT: 'RIGHT',
    LEFT: 'LEFT'
}
DIRECTION_TO_OPPOSITE = {
    UP: DOWN,
    DOWN: UP,
    RIGHT: LEFT,
    LEFT: RIGHT
}
